apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecommerce-cluster
  region: us-east-1 #region AWS 
  version: "1.31" #version de Kubernetes

# Utiliser le VPC existant
vpc:
  id: "vpc-0f0f3806fe9dc91de"  # ← Remplacez par votre VPC ID
  subnets:
    private:
      us-east-1a:
        id: subnet-0fb22389063a61b8f  # ← Subnet Privé A
      us-east-1b:
        id: subnet-048c9e0faaea86fe3  # ← Subnet Privé B

# Node Group (Worker Nodes)
managedNodeGroups:
  - name: ecommerce-nodes
    instanceType: t3.small
    desiredCapacity: 2 #Créer 2 machines EC2 type t3.medium
    minSize: 2 #2 machines (ne jamais descendre en-dessous)
    maxSize: 4 #4 machines (si auto-scaling activé plus tard)
    volumeSize: 20
    privateNetworking: true
    securityGroups:
      attachIDs: ["sg-0d2831c841e29f9b8"]  # ← SG-EKS-Nodes
    iam:
      withAddonPolicies:
        imageBuilder: true #Permet à EKS de construire des images (ex: pour les add-ons) 
        autoScaler: true #Permet à Cluster Autoscaler de fonctionner (si activé plus tard) Peut créer/supprimer des nodes automatiquement
        albIngress: true #Permet à AWS Load Balancer Controller de fonctionner (si activé plus tard) Permet de créer des Load Balancers pour exposer les services Kubernetes Le Ingress Controller peut créer des ALB automatiquement
        cloudWatch: true #Permet à CloudWatch de collecter les logs des nodes
    tags:
      Project: ecommerce-pfe
      Environment: dev
      Component: eks-workers

# Add-ons
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

# CloudWatch Logs
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"] #Permet de collecter les logs Kubernetes dans CloudWatch Logs pour une meilleure observabilité et dépannage. Les types de logs activés incluent les logs d'API, d'audit, d'authentification, du controller manager et du scheduler.

# IAM OIDC Provider (pour IRSA)
iam:
  withOIDC: true #Permet d'utiliser IAM Roles for Service Accounts (IRSA) pour donner des permissions spécifiques aux pods Kubernetes (ex: accès S3, SQS, etc.) sans utiliser de clés d'accès AWS dans les conteneurs. IRSA est une bonne pratique de sécurité recommandée par AWS.